// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI2Dq8EcF352tqGtRdgMlX2drPzQIVEwQ',
    appId: '1:233193760624:web:51c5db49a4fbee100251b5',
    messagingSenderId: '233193760624',
    projectId: 'study-scroll-68e8d',
    authDomain: 'study-scroll-68e8d.firebaseapp.com',
    storageBucket: 'study-scroll-68e8d.firebasestorage.app',
    measurementId: 'G-3NS256J7Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5B1j69PQfodQbOOCLoYtQ00Fnne0IopA',
    appId: '1:233193760624:android:459f876a6065d2700251b5',
    messagingSenderId: '233193760624',
    projectId: 'study-scroll-68e8d',
    storageBucket: 'study-scroll-68e8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqk-nxKknuI9YGFd2mTkUkRXv6vdGhj9c',
    appId: '1:233193760624:ios:22c7e14c74afaab50251b5',
    messagingSenderId: '233193760624',
    projectId: 'study-scroll-68e8d',
    storageBucket: 'study-scroll-68e8d.firebasestorage.app',
    iosBundleId: 'com.example.studyScroll',
  );
}
